# Generated by Django 5.0.6 on 2024-07-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
