# Generated by Django 5.0.6 on 2024-07-17 22:45

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
