# Generated by Django 5.0.6 on 2024-07-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Open', max_length=10),
        ),
    ]
