# Generated by Django 5.0.6 on 2024-07-20 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=22),
        ),
    ]
