# Generated by Django 5.1.1 on 2024-09-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_order_amount_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_name',
            field=models.CharField(default='Guest', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_phone',
            field=models.CharField(default='07769299204', max_length=20),
            preserve_default=False,
        ),
    ]
